version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./index.html:/app/index.html
      - ./app.py:/app/app.py
      - ./functions.js:/app/functions.js
      - ./styles.css:/app/styles.css
      - ./saved_html:/app/saved_html
